MovieShop/MovieShopMVC/Models/ErrorViewModel.cs
namespace MovieShopMVC.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

MovieShop/MovieShopMVC/Controllers/AccountController.cs
namespace MovieShopMVC.Controllers;

public class AccountController
{
    
}

MovieShop/MovieShopMVC/Controllers/AdminController.cs
namespace MovieShopMVC.Controllers;

public class AdminController
{
    
}

MovieShop/MovieShopMVC/Controllers/CastController.cs
namespace MovieShopMVC.Controllers;

public class CastController
{
    
}

MovieShop/MovieShopMVC/Controllers/HomeController.cs
using System.Diagnostics;
using ApplicationCore.Contracts.Services;
using Microsoft.AspNetCore.Mvc;
using MovieShopMVC.Models;

namespace MovieShopMVC.Controllers;

public class HomeController : Controller
{
    private readonly IMovieService movieService;
    
    public HomeController(IMovieService _movieService)
    {
        movieService = _movieService;
    }
    public IActionResult Index()
    { 
        var movies= movieService.GetTop20GrossingMovies();
        return View(movies);
    }

    public IActionResult Privacy()
    {
        return View();
    }

    public IActionResult test()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

MovieShop/MovieShopMVC/Controllers/MoviesController.cs
using ApplicationCore.Contracts.Services;
using Microsoft.AspNetCore.Mvc;

namespace MovieShopMVC.Controllers
{
    public class MoviesController : Controller
    {
        private readonly IMovieService _movieService;
        public MoviesController(IMovieService movieService)
        {
            _movieService = movieService;
        }

        [HttpGet]
        public IActionResult MovieDetails(int id)
        {
            var movie = _movieService.GetMovieDetails(id);
            return View(movie);
        }

        [HttpPost]
        public IActionResult DeleteMovie(int id)
        {
            var movie = _movieService.GetMovieDetails(id);
            if (movie == null)
            {
                return NotFound();
            }

            _movieService.DeleteMovie(id);
            return RedirectToAction("Index","Home");
        }

    }
}

MovieShop/MovieShopMVC/Controllers/UserController.cs
namespace MovieShopMVC.Controllers;

public class UserController
{
    
}

MovieShop/MovieShopMVC/Views/Home/Index.cshtml
@using ApplicationCore.Models
@model IEnumerable<ApplicationCore.Models.MovieCardModel> 


<div class="rounded">
    <div class="container-fluid">
        <div class="row">
            @foreach (var movie in Model)
            { 
                <partial name="_MovieCard" model="movie"/>
            } 
        </div>
    </div>

</div>

MovieShop/MovieShopMVC/Views/Home/test.cshtml
<h1>test</h1>

MovieShop/MovieShopMVC/Views/Movies/MovieDetails.cshtml
@model ApplicationCore.Models.MovieDetailsModel;

<div class="container mt-5">
    <div class=" row">
        <div class="col-md-4">
            <img src="@Model.PosterURL" alt="@Model.Title" class="img-fluid rounded"/>
        </div>
        <div class="col-md-8">
            <h2>@Model.Title</h2>
            <h5 class="text-muted"> @Model.Tagline</h5>
            <p class="mt-3">
                <strong>Overview:</strong>@Model.Overview
            </p>
            <p>
                <strong>Budget:</strong> @Model.Budget.ToString("C")
                <strong>Revenue:</strong>@Model.Revenue.ToString("C")
            </p>
            <div class="mt-3">
                <a asp-action="Edit" asp-controller="Movies" asp-route-id ="@Model.Id"
                   class="btn btn-primary me-2">Edit</a>
                <form asp-action="DeleteMovie" asp-controller="Movies" asp-route-id="@Model.Id" method="post" class="mt-2">
                    <button type="submit" class="btn bg-danger" onclick="return confirm('Are you sure you want to delete  this movie?')">
                        Delete
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>

MovieShop/MovieShopMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - MovieShopMVC</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/MovieShopMVC.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MovieShopMVC</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2025 - MovieShopMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MovieShop/MovieShopMVC/Views/Shared/_MovieCard.cshtml
@model ApplicationCore.Models.MovieCardModel

<div class="col-xl-2 col-lg-3 col-md-4 col-6 mb-4">
    <a asp-controller="Movies" asp-action="MovieDetails" asp-route-id="@Model.Id">
        <img src="@Model.PosterURL" alt="@Model.Title" class="img-fluid"/>
    </a>
</div>